site_name: Dokumentasi SMA

nav:
  - Home: index.md
  - Matematika:
    - Sudut Trigonometri [10]: math/trigonometri.md

theme:
  name: material
  language: id
  font:
    text: Open Sans
  features:
    - navigation.tabs
    - content.tabs.link
  # icon:
  #   repo: fontawesome/brands/git-alt
  palette: 
  - scheme: default
    primary: teal
    accent: indigo
    toggle:
      icon: material/toggle-switch-off-outline
      name: Tema Gelap
  - scheme: slate 
    primary: deep purple
    accent: green
    toggle:
      icon: material/toggle-switch-outline
      name: Tema Terang

markdown_extensions:
  - meta
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js