site_name: Dokumentasi SMA
site_url: https://example.com/

repo_url: https://github.com/FrankyRay/Docs-Pribadi-SMA
repo_name: FrankyRay/Docs-Pribadi-SMA

nav:
  - Home: index.md
  - Misc: mkdocs.md
  - Matematika:
    - Sudut Trigonometri [10]: math/trigonometri.md
    - Polinomial [11]: math/polinomial.md

theme:
  name: material
  language: id
  font:
    text: Open Sans
  features:
    - navigation.tabs
    - content.tabs.link
  # icon:
  #   repo: fontawesome/brands/git-alt
  palette: 
  - scheme: default
    primary: teal
    accent: indigo
    toggle:
      icon: material/toggle-switch-off-outline
      name: Tema Gelap
  - scheme: slate 
    primary: deep purple
    accent: green
    toggle:
      icon: material/toggle-switch-outline
      name: Tema Terang

markdown_extensions:
  - meta
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.superfences
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.tabbed:
      alternate_style: true 
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js