site_name: Dokumentasi SMA
site_url: https://example.com/

repo_url: https://github.com/FrankyRay/Docs-Pribadi-SMA
repo_name: FrankyRay/Docs-Pribadi-SMA

nav:
  - Home: index.md
  - Kelas 10:
    - Matematika: 
      - "[10] Sudut Trigonometri": math/trigonometri.md
  - Kelas 11:
    - Matematika Wajib:
      - Polinomial: math/polinomial.md
      - Interval: math/interval.md
      - Kisi-Kisi Semester 2: math/kisi_11_s2.md
  - Misc:
    - mkdocs.md
    - MathJax: mathjax.md

theme:
  name: material
  language: id
  font:
    text: Open Sans
  features:
    - navigation.tabs
    - navigation.sections
    - content.tabs.link
  palette: 
  - scheme: default
    primary: teal
    accent: indigo
    toggle:
      icon: material/toggle-switch-off-outline
      name: Tema Gelap
  - scheme: slate 
    primary: deep purple
    accent: green
    toggle:
      icon: material/toggle-switch-outline
      name: Tema Terang

markdown_extensions:
  - meta
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.superfences
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.tabbed:
      alternate_style: true 
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js